name: Publish r-stat-301 on DockerHub
on: 
  push: 
    paths: 
      - 'dockerfiles/r-stat-301/Dockerfile'
      - 'dockerfiles/r-stat-301-grading/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: dockerfile_updates # TODO: Testing purposes only, change to main.
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: bump
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        release_name: ${{ steps.bump.outputs.new_tag }}
        body: |
          Changes in this Release
          - Rebuilt r-stat-301 Docker image and published to DockerHub with new tag
          - Rebuilt r-stat-301-grading Docker image and published to DockerHub with new tag
        draft: false
        prerelease: false
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: brianki/r-stat-301-student-test # TODO: Testing purposes only, change to ubcdsci/r-stat-301
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: dockerfiles/r-stat-301
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: brianki/r-stat-301-instructor-test # TODO: Testing purposes only, change to ubcdsci/r-stat-301-grading
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: dockerfiles/r-stat-301-grading
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
